### ISSUE TITLE
[status.e621.ws] Webhook creation failure

### ISSUE THREAD

**Issue by clragon** [OwOWebsites/Primary#1]
### Description

I appear to be unable to create a Webhook on `https://status.e621.ws/webhook`.

### Steps to Reproduce

1. open `https://status.e621.ws/webhook`
2. click "Authorize"
3. ???

### Expected Behavior

When I click "Authorize" I get redirected to a discord authentication prompt to add a webhook to a discord server.

### Actual Behavior

When I click "Authorize" I get redirected to `/`

### Environment

- Operating System: Windows 11 Pro 10.0.22621 Build 22621
- Browser: Google Chrome 112.0.5615.122 / Microsoft Edge 112.0.1722.48
- Version: `status.e621.ws` as of 21.04.23

### Additional Information

In the console I can see that the request to
`https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816`
has failed. I dont know if thats related though.

**Comment by DonovanDMC** [comment]
The link should open https://status.e621.ws/webhook/discord
(minimum currently doesn't work, so just remove the identify scope from the url if you want a minimum authorization)

**Comment by clragon** [comment]
Awesome, directly opening `https://status.e621.ws/webhook/discord` works! 
The "Authorize" button always seems to redirect me to just `https://status.e621.ws/` though.

**Comment by DonovanDMC** [comment]
I've both fixed the links (I changed the structure a little bit part way through without thinking about where the old urls were referenced), and changed the redirect to only redirect from the root (Like what it's supposed to do, redirecting https://e621.ws to https://status.e621.ws) 

I need to get away from express.. in what world does `use("/")` mean ALL paths, and `get("/")` mean the root
